services:
  mongo:
    image: mongo:7
    container_name: sport_mongo_Craievich
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sport_backend_Craievich
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      PORT: 3001
      MONGO_URL: mongodb://mongo:27017/sport
      JWT_SECRET: segreto123
      JWT_EXPIRES: 7d

volumes:
  mongo_data:
